inherit_gem:
    rubocop-rails-omakase: rubocop.yml

AllCops:
    NewCops: enable

# Your Custom Overrides
Layout/SpaceInsideArrayLiteralBrackets:
    Enabled: false

Layout/IndentationWidth:
    Enabled: true
    Width: 4

Layout/IndentationConsistency:
    Enabled: true
    EnforcedStyle: normal

Layout/CaseIndentation:
    Enabled: true
    IndentOneStep: true
